export const GET_ARTISTS = 'GET_ARTISTS';
export const GET_ARTISTS_SUCCESS = 'GET_ARTISTS_SUCCESS';
export const GET_ARTISTS_ERROR = 'GET_ARTISTS_ERROR';

export const ADD_ARTIST = 'ADD_ARTIST';
export const ADD_ARTIST_SUCCESS = 'ADD_ARTIST_SUCCESS';
export const ADD_ARTIST_ERROR = 'ADD_ARTIST_ERROR';

export const GET_ARTIST = 'GET_ARTIST';
export const GET_ARTIST_SUCCESS = 'GET_ARTIST_SUCCESS';
export const GET_ARTIST_ERROR = 'GET_ARTIST_ERROR';

export const EDIT_ARTIST = 'EDIT_ARTIST';
export const EDIT_ARTIST_SUCCESS = 'EDIT_ARTIST_SUCCESS';
export const EDIT_ARTIST_ERROR = 'EDIT_ARTIST_ERROR';

export const DELETE_ARTIST = 'DELETE_ARTIST';
export const DELETE_ARTIST_SUCCESS = 'DELETE_ARTIST_SUCCESS';
export const DELETE_ARTIST_ERROR = 'DELETE_ARTIST_ERROR';
